#include <stdio.h>
#include <stdint.h>
#include <pthread.h>
#include <unistd.h>
#include <semaphore.h>
#include <fcntl.h>
#include <sys/stat.h>

// Global Semaphore Pointer
sem_t *items_in_queue;

/**
 * @brief Initialize the Semaphore to 0 tokens
 * @param const char identifier pointer
 * @return sem_t pointer
 */
sem_t *init_semaphore(const char *identifier)
{
    sem_unlink(identifier);
    return sem_open(identifier, O_CREAT, 0644, 0);
}

/**
 * @brief Destroys and unlink the Semaphore
 * @param sem_t semaphore pointer
 * @return void
 */
void destroy_semaphore(sem_t *semaphore, const char *identifier)
{
    sem_close(semaphore);
    sem_unlink(identifier);
}

/**
 * @brief Producer's pthread callbacks that generates messages
 * @param void arg pointer 
 * @return void pointer
 */
void *gen_message(void *arg)
{
    uint8_t *iter = (uint8_t *)arg;
    if(iter == NULL) return NULL;
    
    for(uint8_t i = 0; i < *iter; i++)
    {
        printf("Packet extracted [%d]\n", i);
        sleep(1);
        sem_post(items_in_queue);
    }

    return NULL;
}

/**
 * @brief Consumer's pthread callbacks that outputs messages
 * @param void arg pointer 
 * @return void pointer
 */
void *consume_message(void *arg)
{
    uint8_t *iter = (uint8_t *)arg;
    if(iter == NULL) return NULL;
   
    printf("[Consumer] Booting up slowly... sleeping for 3 seconds.\n");
    sleep(3);

    for(uint8_t i = 0; i < *iter; i++)
    {
        // wait until a token is generated by the producer
        sem_wait(items_in_queue);

        printf("Packet consumed [%d]\n", i);
        sleep(1);
    }

    return NULL;
}

int main(void)
{
    uint8_t messages = 5;

    items_in_queue = init_semaphore("/items_queue");
    pthread_t producer, consumer;
    
    pthread_create(&producer, NULL, gen_message, (void *)&messages);
    pthread_create(&consumer, NULL, consume_message, (void *)&messages);
    
    pthread_join(producer, NULL);
    pthread_join(consumer, NULL);

    destroy_semaphore(items_in_queue, "/items_queue");
    return 0;
}
